spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_db
    username: kiend
    password: dang
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db_log/db_update-log.yaml
server:
  port: 8000